### ISSUE TITLE
Where to execute of buffer local variables code

### ISSUE THREAD

**Issue by webappzero** [jingtaozf/literate-clojure#1]
**Should the instructions below ([source located here](https://github.com/jingtaozf/literate-clojure#define-buffer-local-variables-to-specifiy-current-literate-language-and-default-load-type)) be added to my Emacs Config file?** The docs didn't explicitly say. _(Thank you for sharing this exciting library!)_

> 
> Define buffer local variables to specifiy current literate language and default load type
> 
> `(defvar literate-lang nil)`
> `(make-variable-buffer-local 'literate-lang)`
> `(defvar literate-load nil)`
> `(make-variable-buffer-local 'literate-load)`

**Comment by jingtaozf** [comment]
Yes, you can add them to your Emacs config file, to simplify the insert command.
